types:
  34132:
    id: 34132
    marketGroup: 1942
    name: Pilot's Body Resculpt Certificate
    portionSize: 1
    published: true
    volume: 0.01
  34133:
    id: 34133
    marketGroup: 1942
    name: Multiple Pilot Training Certificate
    portionSize: 1
    published: true
    volume: 0.01
  40519:
    id: 40519
    marketGroup: 2358
    name: Skill Extractor
    portionSize: 1
    published: true
    volume: 0.01
  89956:
    id: 89956
    name: Pilot's Body Resculpt Certificate (Untradeable)
    portionSize: 1
    published: true
    volume: 0.01
