types:
  37258:
    canfitshipgroup01: 1657
    canfitshipgroup02: 1404
    canfitshipgroup03: 1406
    hisecmodifier: 1.0
    hp: 40.0
    id: 37258
    lowsecmodifier: 1.2
    marketGroup: 2345
    mass: 200.0
    maxgroupfitted: 1
    name: Standup L-Set Point Defense Battery Control I
    nullsecmodifier: 1.2
    portionSize: 1
    published: true
    radius: 100.0
    requiredskill1: 26252
    requiredskill1level: 1
    rigsize: 3
    securitymodifier: 1
    structureitemvisualflag: 1
    structurerigpdcapusebonus: -30
    structurerigpdrangebonus: 500
    techlevel: 1
    upgradecost: 100
    volume: 20.0
  37259:
    canfitshipgroup01: 1657
    canfitshipgroup02: 1404
    canfitshipgroup03: 1406
    hisecmodifier: 1.0
    hp: 40.0
    id: 37259
    lowsecmodifier: 1.2
    marketGroup: 2345
    mass: 200.0
    maxgroupfitted: 1
    name: Standup L-Set Point Defense Battery Control II
    nullsecmodifier: 1.2
    portionSize: 1
    published: true
    radius: 100.0
    requiredskill1: 26252
    requiredskill1level: 1
    rigsize: 3
    securitymodifier: 1
    structureitemvisualflag: 1
    structurerigpdcapusebonus: -35
    structurerigpdrangebonus: 600
    techlevel: 2
    upgradecost: 150
    volume: 20.0
