gameclient:
   fetcher:
      update:
         skip: true

esi:
   alliance:
      info:
         update:
            skip: false
   character:
      affiliation:
         update:
            skip: false
      info:
         update:
            skip: false
   conflicts:
      war:
         info:
            update:
               skip: true
   corporation:
      info:
         update:
            skip: false
   faction:
      info:
         update:
            skip: false
   npc:
      lpcorporation:
         update:
            delayUpdated: 3600
            skip: false
   resolve:
      name:
         update:
            skip: false
   trade:
      contract:
         info:
            update:
               skip: false
         region:
            update:
               skip: false
      history:
         update:
            skip: false
      market:
         update:
            skip: false
      prices:
         update:
            skip: false
   universe:
      statsjumps:
         update:
            skip: false
      statskills:
         update:
            skip: false
jcesi:
   manager:
      default:
         skip: true
      delay: 0
      period: 2000

sde:
   fetcher:
      update:
         skip: false